language: c
sudo: false
cache:
  directories:
  - ~/arduino_ide
  - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
  - PRETTYNAME="Frequency Detector Arduino Library"
  - CLI_VERSION=latest
#  matrix:
# matrix does not work -> Error: fork/exec /bin/avr-g++: no such file or directory (for ATTinyCore:avr:attinyx5)
#    - BOARD=arduino:avr:uno
#    - BOARD=ATTinyCore:avr:attinyx5
before_install:
- echo "Downloading latest CLI version of the Arduino IDE..."
- wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
- echo "Extracting the Arduino IDE..."
- tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
- echo "Moving Arduino IDE..."
- mkdir -p $HOME/bin
- mv arduino-cli-*-linux64 $HOME/bin/arduino-cli
- export PATH=$PATH:$HOME/bin
#- echo $PWD
#- ls -la
- echo "Update platform indexes..."
# parameter is needed :-(
- arduino-cli core update-index --config-file ./.cli-config.yml
- echo "Install board..."
#- if [[ "$BOARD" =~ "arduino:avr:" ]]; then
#      arduino-cli core install arduino:avr;
#  fi
# parameter is needed :-(
- arduino-cli core install arduino:avr
- arduino-cli core install ATTinyCore:avr --config-file ./.cli-config.yml
- echo "Show all boards now available..."
- arduino-cli board listall
#- buildExampleSketch() { arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/$1; }
install:
- mkdir -p $HOME/Arduino/libraries
- ln -s $PWD $HOME/Arduino/libraries/.
script:
- arduino-cli compile --warnings all --fqbn arduino:avr:uno examples/SimpleFrequencyDetector
- arduino-cli compile --warnings all --fqbn arduino:avr:uno examples/WhistleSwitch
- arduino-cli compile --verbose --warnings all --fqbn ATTinyCore:avr:attinyx5 examples/WhistleSwitch
notifications:
  email:
    on_success: always
    on_failure: always
